import { ArrowRight,ChartLineUp,ClipboardText,Cube,Package,Receipt,WarningCircle } from "@phosphor-icons/react";
import { Link } from "react-router-dom";
import { formatMoney,movementLabel,useData } from "../data.jsx";
import { PageHeader,ProductImage } from "../components/AppShell.jsx";

export function DashboardPage() {
  const { state }=useData(); const metrics=[
    ["Sales today",formatMoney(state.dashboard.salesToday),Receipt,"/pos"],["Orders today",state.dashboard.ordersToday,ChartLineUp,"/staff#web-orders"],["Low stock",state.dashboard.lowStock,WarningCircle,"/inventory?view=low"],["Out of stock",state.dashboard.outOfStock,Package,"/inventory?view=low"],["Pending adjustments",state.dashboard.pendingAdjustments,ClipboardText,"/stock-counts"],["Counts in progress",state.dashboard.activeCounts,Cube,"/stock-counts"],
  ];
  const low=state.products.filter(product=>product.totalStock<=product.minStock).slice(0,5);
  return <div className="page dashboard-page"><PageHeader eyebrow="Main Shop · live operations" title="Good morning, Alex" description="The shop is synced. Here is what needs attention today." actions={<Link className="button primary" to="/search">Find a component <ArrowRight/></Link>}/><div className="metric-grid">{metrics.map(([label,value,Icon,path])=><Link to={path} className="metric" key={label}><Icon weight="duotone"/><span><small>{label}</small><strong>{value}</strong></span><ArrowRight/></Link>)}</div><div className="dashboard-grid"><section className="content-panel"><div className="panel-title"><h2>Recent stock movements</h2><Link to="/inventory?view=movements">View ledger</Link></div><div className="compact-movements">{state.movements.slice(0,7).map(item=><div key={item.id}><i className={`movement-icon ${item.quantity>0?"in":"out"}`}>{item.quantity>0?"+":"−"}</i><span><strong>{item.sku} · {movementLabel(item.type)}</strong><small>{item.reason}</small></span><b className={item.quantity>0?"qty-in":"qty-out"}>{item.quantity>0?"+":""}{item.quantity}</b><time>{new Date(item.created_at).toLocaleDateString()}</time></div>)}</div></section><section className="content-panel"><div className="panel-title"><h2>Low stock watch</h2><Link to="/inventory?view=low">Manage</Link></div><div className="low-stock-list">{low.length?low.map(product=><Link to={`/products/${product.id}`} key={product.id}><ProductImage product={product}/><span><strong>{product.shortName}</strong><small>{product.primaryLocation}</small></span><b>{product.totalStock.toLocaleString()}<small> / min {product.minStock}</small></b></Link>):<p className="all-good">All products are above their minimum level.</p>}</div></section><section className="content-panel searches-panel"><div className="panel-title"><h2>Top searches</h2><span>Last 7 days</span></div><div className="search-rank">{[["220uf 25v",184],["2A104J",149],["IRF3205",126],["10k 1/4w",98],["ESP32",84]].map(([query,count],index)=><Link to={`/search?q=${encodeURIComponent(query)}`} key={query}><b>{index+1}</b><code>{query}</code><span>{count} searches</span></Link>)}</div></section><section className="content-panel"><div className="panel-title"><h2>Recent sales</h2><Link to="/pos">Open POS</Link></div>{state.sales.length?<div className="sales-list">{state.sales.slice(0,6).map(sale=><div key={sale.id}><span><strong>{sale.reference}</strong><small>{sale.customer} · {sale.payment_method}</small></span><b>{formatMoney(sale.total)}</b></div>)}</div>:<div className="quiet-empty"><Receipt/><span>No demo sales yet</span><small>Complete a sale in POS and it will appear here.</small></div>}</section></div></div>;
}
