import { useEffect,useRef,useState } from "react";
import { Barcode,CheckCircle,ClipboardText,Crosshair,Cube,MapPin,Package,Printer,Scan,ShoppingCart,Truck,Warning,XCircle } from "@phosphor-icons/react";
import { Link,useNavigate,useSearchParams } from "react-router-dom";
import { formatMoney,useData,useProduct } from "../data.jsx";
import { Modal,PageHeader,ProductImage,RackMap,ScannerModal } from "../components/AppShell.jsx";

export function LocationsPage() {
  const { state }=useData(); const [selectedId,setSelectedId]=useState("b3-12"); const selected=state.locations.find(location=>location.id===selectedId)||state.locations[0]; const products=state.products.filter(product=>product.locations.some(location=>location.id===selected.id)).map(product=>({...product,locationQty:product.locations.find(location=>location.id===selected.id).quantity}));
  const zones=[...new Set(state.locations.map(location=>location.zone))];
  return <div className="page"><PageHeader eyebrow="Physical shop model" title="Locations" description="Browse every zone, rack, shelf, bin, and drawer with live product quantities."/><div className="location-browser"><aside className="location-tree">{zones.map(zone=><div key={zone}><h3>{zone}</h3>{state.locations.filter(location=>location.zone===zone).map(location=><button className={selected.id===location.id?"active":""} onClick={()=>setSelectedId(location.id)} key={location.id}><MapPin/><span><strong>{location.code}</strong><small>Rack {location.rack} · Shelf {location.shelf} · Bin {location.bin}</small></span><b>{location.total_units.toLocaleString()}</b></button>)}</div>)}</aside><section className="location-content"><div className="location-hero"><div><span className="eyebrow">{selected.zone}</span><h1>{selected.code}</h1><p>{selected.name} · Rack {selected.rack} → Shelf {selected.shelf} → Bin {selected.bin}</p></div><div className="capacity"><small>Capacity usage</small><strong>{Math.round(selected.total_units/selected.capacity*100)}%</strong><span>{selected.total_units.toLocaleString()} / {selected.capacity.toLocaleString()} pcs</span></div></div><RackMap locationCode={selected.code}/><div className="panel-title location-product-title"><h2>Products stored here</h2><span>{products.length} SKUs · barcode <code>LOC-{selected.code}</code></span></div><div className="location-products">{products.map(product=><Link to={`/products/${product.id}`} key={product.id}><ProductImage product={product}/><span><strong>{product.shortName}</strong><small>{product.name}</small><code>{product.sku}</code></span><b>{product.locationQty.toLocaleString()} pcs</b></Link>)}</div></section></div></div>;
}

function NewCountModal({ onClose }) {
  const { state,mutate }=useData(); const [params]=useSearchParams(); const preselected=useProduct(params.get("product")); const [scopeType,setScopeType]=useState("RACK"); const [scopeCode,setScopeCode]=useState("Rack B"); const [productId,setProductId]=useState(preselected?.id||"2a104j"); const product=state.products.find(item=>item.id===productId); const [locationId,setLocationId]=useState(product?.locations[0]?.id||"b3-12"); const expected=product?.locations.find(location=>location.id===locationId)?.quantity||0; const [countedQty,setCountedQty]=useState(expected);
  const submit=async event=>{event.preventDefault();await mutate("/api/stock-counts",{name:`${scopeCode} — ${new Date().toLocaleDateString()}`,scopeType,scopeCode,productId,locationId,countedQty:Number(countedQty),user:"Alex Turner"},"Discrepancy submitted for supervisor approval");onClose();};
  return <Modal title="New stock count" onClose={onClose}><form className="stack-form" onSubmit={submit}><label>Scope<select value={scopeType} onChange={event=>setScopeType(event.target.value)}>{[["BRANCH","Entire branch"],["ZONE","Zone"],["RACK","Rack"],["SHELF","Shelf"],["BIN","Bin / drawer"]].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Scope name<input value={scopeCode} onChange={event=>setScopeCode(event.target.value)} placeholder="Rack B"/></label><label>Product<select value={productId} onChange={event=>{setProductId(event.target.value);setLocationId(state.products.find(item=>item.id===event.target.value)?.locations[0]?.id||"")}}>{state.products.map(item=><option key={item.id} value={item.id}>{item.sku} — {item.shortName}</option>)}</select></label><label>Count location<select value={locationId} onChange={event=>{setLocationId(event.target.value);const next=product.locations.find(item=>item.id===event.target.value)?.quantity||0;setCountedQty(next)}}>{product?.locations.map(location=><option key={location.id} value={location.id}>{location.code} — expected {location.quantity}</option>)}</select></label><div className="count-entry"><span><small>Expected</small><strong>{expected.toLocaleString()}</strong></span><label>Counted<input type="number" min="0" value={countedQty} onChange={event=>setCountedQty(event.target.value)}/></label><span className={Number(countedQty)-expected===0?"neutral":Number(countedQty)-expected>0?"qty-in":"qty-out"}><small>Difference</small><strong>{Number(countedQty)-expected>0?"+":""}{Number(countedQty)-expected}</strong></span></div><div className="domain-note"><ClipboardText/>Inventory is not changed now. A supervisor must approve the discrepancy.</div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" type="submit">Submit count</button></div></form></Modal>;
}

export function StockCountsPage() {
  const { state,mutate }=useData(); const [createOpen,setCreateOpen]=useState(false); const approve=async id=>mutate(`/api/stock-counts/${id}/approve`,{approver:"Supervisor Mei"},"Count approved and adjustment movement created");
  return <div className="page"><PageHeader eyebrow="Controlled reconciliation" title="Stock counts" description="Count first, review discrepancies, then create approved ledger adjustments." actions={<button className="primary" onClick={()=>setCreateOpen(true)}><ClipboardText/>New Stock Count</button>}/><div className="count-progress"><div><strong>Rack B — cycle count</strong><span>In progress</span></div><div className="progress-bar"><i style={{width:"60%"}}/><span>18 / 30 locations counted</span></div></div><div className="count-cards">{state.counts.map(count=><section className="count-card" key={count.id}><header><div><span className={`status-pill ${count.status.toLowerCase()}`}>{count.status.replaceAll("_"," ")}</span><h2>{count.name}</h2><p>{count.scope_type} · {count.scope_code} · counted by {count.counted_by}</p></div><b>{count.pending_count} pending</b></header>{count.items.map(item=><div className="count-item" key={item.id}><span><strong>{item.sku}</strong><small>{item.product_name} · {item.location_code}</small></span><span><small>Expected</small><b>{item.expected_qty.toLocaleString()}</b></span><span><small>Counted</small><b>{item.counted_qty.toLocaleString()}</b></span><span className={item.difference===0?"neutral":item.difference>0?"qty-in":"qty-out"}><small>Difference</small><b>{item.difference>0?"+":""}{item.difference}</b></span><i className={`status-pill ${item.status.toLowerCase()}`}>{item.status}</i></div>)}{count.status==="PENDING_APPROVAL"&&<footer className="count-actions"><button>Request recount</button><button>Reject</button><button className="primary" onClick={()=>approve(count.id)}><CheckCircle/>Approve discrepancy</button></footer>}</section>)}{!state.counts.length&&<div className="quiet-empty"><ClipboardText/><span>No stock counts yet</span><small>Create a count for a rack, shelf, or bin.</small></div>}</div>{createOpen&&<NewCountModal onClose={()=>setCreateOpen(false)}/>}</div>;
}

function Code128Barcode({ value }) {
  const canvasRef=useRef(null);
  useEffect(()=>{let active=true;import("bwip-js").then(({default:bwipjs})=>{if(active&&canvasRef.current)bwipjs.toCanvas(canvasRef.current,{bcid:"code128",text:value,scale:2,height:12,includetext:false,backgroundcolor:"FFFFFF"})});return()=>{active=false}},[value]);
  return <canvas ref={canvasRef} className="barcode-canvas" aria-label={`Code 128 barcode ${value}`}/>;
}

export function LabelsPage() {
  const { state }=useData(); const [params]=useSearchParams(); const [type,setType]=useState("product"); const [productId,setProductId]=useState(params.get("product")||"2a104j"); const [locationId,setLocationId]=useState("b3-12"); const [copies,setCopies]=useState(1); const [size,setSize]=useState("50 × 30 mm"); const product=state.products.find(item=>item.id===productId); const location=state.locations.find(item=>item.id===locationId);
  const barcodeValue=type==="shelf"?`LOC-${location.code}`:product.barcode;
  return <div className="page labels-page"><PageHeader eyebrow="Browser print · thermal ready" title="Barcode labels" description="Generate Code 128-ready product and location labels without changing catalogue data."/><div className="label-workspace"><section className="label-controls"><div className="template-buttons">{[["product","Product Label",Package],["price","Price Label",Printer],["shelf","Shelf / Bin",MapPin],["box","Box Label",Cube]].map(([value,label,Icon])=><button className={type===value?"active":""} onClick={()=>setType(value)} key={value}><Icon weight="duotone"/><span>{label}</span></button>)}</div>{type==="shelf"?<label>Location<select value={locationId} onChange={event=>setLocationId(event.target.value)}>{state.locations.map(item=><option value={item.id} key={item.id}>{item.code} — {item.name}</option>)}</select></label>:<label>Product<select value={productId} onChange={event=>setProductId(event.target.value)}>{state.products.map(item=><option value={item.id} key={item.id}>{item.sku} — {item.shortName}</option>)}</select></label>}<label>Label size<select value={size} onChange={event=>setSize(event.target.value)}><option>50 × 30 mm</option><option>40 × 25 mm</option><option>70 × 40 mm</option></select></label><label>Copies<input type="number" min="1" max="100" value={copies} onChange={event=>setCopies(event.target.value)}/></label><button className="primary print-button" onClick={()=>window.print()}><Printer/>Print {copies} {Number(copies)===1?"label":"labels"}</button></section><section className="label-preview-area"><span>Print preview · {size}</span><div className={`print-label ${type}`}><header>{type==="shelf"?location.code:product.sku}</header>{type!=="shelf"&&<><strong>{product.shortName}</strong><p>{product.name}</p></>}{type==="price"&&<b>${product.retailPrice.toFixed(3)}</b>}{type==="box"&&<div className="box-qty">QTY <strong>100</strong></div>}{type==="shelf"&&<p>{location.zone} · Rack {location.rack} · Shelf {location.shelf}</p>}<Code128Barcode value={barcodeValue}/><code>{barcodeValue}</code></div><small>Barcode content uses the existing product/location identifier. Browser print is enabled for M1.</small></section></div></div>;
}

const nextWebOrderStatus = Object.freeze({ NEW:["CONFIRMED","Confirm"],CONFIRMED:["READY","Mark ready"],READY:["COMPLETED","Complete"] });

function WebOrderCard({ order }) {
  const { mutate }=useData(); const nextStatus=nextWebOrderStatus[order.status]; const isTerminal=["COMPLETED","CANCELLED"].includes(order.status);
  const changeStatus=status=>mutate(`/api/web-orders/${order.id}/status`,{status,user:"Alex Turner"},`Order ${order.reference} is now ${status.toLowerCase()}`);
  return <article><div><span className={`status-pill ${order.status.toLowerCase()}`}>{order.status}</span><strong>{order.reference}</strong><small>{order.customer_name} · {order.phone}</small></div><div><strong>{order.items.reduce((sum,item)=>sum+item.quantity,0)} pcs</strong><small>{order.items.map(item=>`${item.sku} × ${item.quantity}`).join(" · ")}</small></div><div><strong>{formatMoney(order.subtotal)}</strong><small>{order.fulfillment_method}{order.address?` · ${order.address}`:""}</small></div><div className="web-order-actions">{nextStatus&&<button className="primary" onClick={()=>changeStatus(nextStatus[0])}><CheckCircle/>{nextStatus[1]}</button>}{!isTerminal&&<button className="danger" onClick={()=>changeStatus("CANCELLED")}><XCircle/>Cancel</button>}</div></article>;
}

export function StaffPage() {
  const { state }=useData(); const navigate=useNavigate(); const [scanOpen,setScanOpen]=useState(false); const [query,setQuery]=useState(""); const actions=[["/search","Search",Scan,"Find by value, SKU, or alias"],[null,"Scan Barcode",Barcode,"Camera or scanner fallback"],["/locations","Locate Product",Crosshair,"Highlight rack, shelf, and bin"],["/stock-counts","Count",ClipboardText,"Enter physical quantities"],["/products/2a104j","Move",Truck,"Transfer between bins"],["/inventory?view=movements","Damage / Loss",Warning,"Request controlled movement"],["/inventory","Receive",Package,"Record purchase receipt"],["/labels","Print Label",Printer,"Product and shelf labels"]];
  const search=event=>{event.preventDefault();const normalizedQuery=query.trim();if(!normalizedQuery)return;navigate(`/search?q=${encodeURIComponent(normalizedQuery)}`);};
  return <div className="page staff-page"><PageHeader eyebrow="Mobile staff workspace" title="What do you need to do?" description="Fast actions for the shop floor, counter, warehouse, and incoming online orders."/><form className="staff-quick-search" onSubmit={search}><Scan/><input value={query} onChange={event=>setQuery(event.target.value)} aria-label="Search components" placeholder="Search or scan a component…"/><button type="button" onClick={()=>setScanOpen(true)}><Barcode/>Scan</button></form><div className="staff-actions">{actions.map(([path,label,Icon,description])=>path?<Link to={path} key={label}><Icon weight="duotone"/><span><strong>{label}</strong><small>{description}</small></span></Link>:<button onClick={()=>setScanOpen(true)} key={label}><Icon weight="duotone"/><span><strong>{label}</strong><small>{description}</small></span></button>)}</div><section className="content-panel web-order-panel" id="web-orders"><div className="panel-title"><h2><ShoppingCart/> Online orders</h2><span>{state.webOrders.filter(order=>!["COMPLETED","CANCELLED"].includes(order.status)).length} active</span></div>{state.webOrders.length?<div className="web-order-list">{state.webOrders.map(order=><WebOrderCard order={order} key={order.id}/>)}</div>:<div className="quiet-empty"><ShoppingCart/><span>No online orders yet</span><small>Orders submitted through the public store will appear here.</small></div>}</section><section className="content-panel staff-recent"><div className="panel-title"><h2>Recently handled</h2><span>Main Shop</span></div><div><Link to="/products/2a104j"><strong>2A104J</strong><span>Counter C04 · 350 pcs</span></Link><Link to="/products/irf3205"><strong>IRF3205</strong><span>Warehouse W2-08 · 240 pcs</span></Link><Link to="/products/lm358"><strong>LM358</strong><span>IC Drawer C04B · 120 pcs</span></Link></div></section>{scanOpen&&<ScannerModal onClose={()=>setScanOpen(false)}/>}</div>;
}
