import { useMemo,useState } from "react";
import { Eye,FilePlus,MagnifyingGlass,NotePencil,Printer } from "@phosphor-icons/react";
import { Link } from "react-router-dom";
import { formatMoney,useData } from "../data.jsx";
import { Modal,PageHeader,ProductImage } from "../components/AppShell.jsx";

function ProductForm({ product,onClose }) {
  const { mutate }=useData();
  const [form,setForm]=useState(product||{ id:"",sku:"",partNumber:"",barcode:"",name:"",shortName:"",category:"Capacitors",manufacturer:"",aliases:[],description:"",retailPrice:.02,costPrice:.01,minStock:100,active:true,specs:{},customerPrices:{Technician:.018,Dealer:.016,Distributor:.014},priceTiers:[{minQty:100,price:.018},{minQty:1000,price:.014}] });
  const [aliases,setAliases]=useState((form.aliases||[]).join(", ")); const [specs,setSpecs]=useState(Object.entries(form.specs||{}).map(([key,value])=>`${key}: ${value}`).join("\n"));
  const update=(field,value)=>setForm(current=>({...current,[field]:value}));
  const submit=async event=>{event.preventDefault();const parsedSpecs=Object.fromEntries(specs.split("\n").map(line=>line.split(":")).filter(parts=>parts.length>1).map(([key,...value])=>[key.trim(),value.join(":").trim()]));await mutate("/api/products",{...form,id:form.id||form.sku.toLowerCase().replace(/[^a-z0-9]+/g,"-"),aliases:aliases.split(",").map(value=>value.trim()).filter(Boolean),specs:parsedSpecs},product?"Product updated":"Product created");onClose();};
  return <Modal title={product?`Edit ${product.sku}`:"New electronics product"} onClose={onClose} wide><form className="product-form" onSubmit={submit}><div className="form-grid"><label>Product name<input required value={form.name} onChange={event=>update("name",event.target.value)} placeholder="0.1µF 100V Polyester Film Capacitor"/></label><label>Short name<input required value={form.shortName} onChange={event=>update("shortName",event.target.value)} placeholder="2A104J"/></label><label>SKU<input required value={form.sku} onChange={event=>update("sku",event.target.value)}/></label><label>Part number<input required value={form.partNumber} onChange={event=>update("partNumber",event.target.value)}/></label><label>Barcode<input required value={form.barcode} onChange={event=>update("barcode",event.target.value)}/></label><label>Category<select value={form.category} onChange={event=>update("category",event.target.value)}>{["Capacitors","Resistors","ICs","MOSFETs","Diodes","Boards","Connectors","Relays","Sensors","Tools"].map(value=><option key={value}>{value}</option>)}</select></label><label>Manufacturer<input required value={form.manufacturer} onChange={event=>update("manufacturer",event.target.value)}/></label><label>Retail price<input type="number" min="0" step="0.001" value={form.retailPrice} onChange={event=>update("retailPrice",Number(event.target.value))}/></label><label>Cost price<input type="number" min="0" step="0.001" value={form.costPrice} onChange={event=>update("costPrice",Number(event.target.value))}/></label><label>Minimum stock<input type="number" min="0" value={form.minStock} onChange={event=>update("minStock",Number(event.target.value))}/></label><label className="full">Aliases<input value={aliases} onChange={event=>setAliases(event.target.value)} placeholder="100nf, 0.1uf, 104, old item code"/></label><label className="full">Description<textarea value={form.description} onChange={event=>update("description",event.target.value)}/></label><label className="full">Technical attributes <small>One “Name: Value” per line</small><textarea value={specs} onChange={event=>setSpecs(event.target.value)} placeholder={'Capacitance: 100nF\nVoltage: 100V\nTolerance: ±5%\nPackage: Radial'}/></label></div><div className="form-summary"><strong>Included M1 pricing</strong><span>Technician {formatMoney(form.customerPrices?.Technician||form.retailPrice)}</span><span>Dealer {formatMoney(form.customerPrices?.Dealer||form.retailPrice)}</span><span>Distributor {formatMoney(form.customerPrices?.Distributor||form.retailPrice)}</span><span>{form.priceTiers?.length||0} quantity breaks</span></div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" type="submit">Save product</button></div></form></Modal>;
}

export function ProductsPage() {
  const { state }=useData(); const [query,setQuery]=useState(""); const [category,setCategory]=useState("All"); const [stock,setStock]=useState("All"); const [location,setLocation]=useState("All"); const [page,setPage]=useState(1); const [editing,setEditing]=useState(null);
  const categories=["All",...new Set(state.products.map(product=>product.category))]; const locations=["All",...new Set(state.locations.map(item=>item.code))];
  const filtered=useMemo(()=>state.products.filter(product=>(!query||[product.name,product.sku,product.partNumber].join(" ").toLowerCase().includes(query.toLowerCase()))&&(category==="All"||product.category===category)&&(stock==="All"||(stock==="Low"&&product.totalStock<=product.minStock)||(stock==="In Stock"&&product.totalStock>0)||(stock==="Out"&&product.totalStock===0))&&(location==="All"||product.locations.some(item=>item.code===location))),[state.products,query,category,stock,location]);
  const pageSize=8; const pages=Math.max(1,Math.ceil(filtered.length/pageSize)); const rows=filtered.slice((page-1)*pageSize,page*pageSize);
  return <div className="page"><PageHeader eyebrow="Catalogue control" title="Products" description="One electronics catalogue shared by Search, POS, staff, and the storefront." actions={<button className="primary" onClick={()=>setEditing({})}><FilePlus/>New Product</button>}/><div className="filter-bar"><label className="filter-search"><MagnifyingGlass/><input value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} placeholder="Search SKU, part number, product…"/></label><select value={category} onChange={event=>{setCategory(event.target.value);setPage(1)}}>{categories.map(value=><option key={value}>{value}</option>)}</select><select value={stock} onChange={event=>setStock(event.target.value)}>{["All","In Stock","Low","Out"].map(value=><option key={value}>{value}</option>)}</select><select value={location} onChange={event=>setLocation(event.target.value)}>{locations.map(value=><option key={value}>{value}</option>)}</select></div><div className="data-table product-table"><div className="table-head"><span>Product</span><span>SKU / part</span><span>Category</span><span>Retail</span><span>Stock</span><span>Location</span><span>Status</span><span>Actions</span></div>{rows.map(product=><div className="table-row" key={product.id}><span className="table-product"><ProductImage product={product}/><span><strong>{product.name}</strong><small>{product.manufacturer}</small></span></span><span><code>{product.sku}</code><small>{product.partNumber}</small></span><span>{product.category}</span><span className="mono accent">{formatMoney(product.retailPrice)}</span><span><strong>{product.totalStock.toLocaleString()}</strong><small>min {product.minStock}</small></span><span><code>{product.primaryLocation}</code></span><span><i className={`status-dot ${product.active?"ok":"off"}`}/>{product.active?"Active":"Inactive"}</span><span className="row-actions"><Link title="View" to={`/products/${product.id}`}><Eye/></Link><button title="Edit" onClick={()=>setEditing(product)}><NotePencil/></button><Link title="Print label" to={`/labels?product=${product.id}`}><Printer/></Link></span></div>)}</div><div className="pagination"><span>{filtered.length} products</span><div><button disabled={page===1} onClick={()=>setPage(value=>value-1)}>Previous</button><span>Page {page} of {pages}</span><button disabled={page===pages} onClick={()=>setPage(value=>value+1)}>Next</button></div></div>{editing&&<ProductForm product={editing.id?editing:null} onClose={()=>setEditing(null)}/>}</div>;
}
